version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 2703
      MYSQL_DATABASE: job_data
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: python_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=job_data
      - DB_USER=root
      - DB_PASS=2703
    volumes:
      - .:/app
    command: ["python", "main.py"]

volumes:
  mysql_data:
